import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { createPrismaClient } from "@samma/database";
import { sammaAdapter, resolveDatabaseSession, revokeAccountSessions } from "../../apps/web/lib/auth-adapter";
import { canReadStoredRecord } from "../../apps/web/lib/record-access";
const db = createPrismaClient();
const tag = `auth-test-${randomUUID()}`;
const accounts: string[] = [], companies: string[] = [], definitions: string[] = [];
try {
  for (let i = 0; i < 3; i++) accounts.push((await db.account.create({ data: { primaryEmail: `${tag}-${i}@example.test`, emailVerified: true, person: { create: { displayName: `Synthetic ${i}` } } } })).id);
  const [owner, outsider, lawyer] = accounts as [string, string, string];
  const issuer = "https://identity.example.test/realms/test";
  const identity = await db.accountIdentity.create({ data: { accountId: owner, provider: issuer, providerSubject: tag } });
  const context = { identityId: identity.id, accountId: owner, mfaSatisfied: false };
  const adapter = sammaAdapter(db, issuer, context);
  assert.equal((await adapter.getUserByAccount!({ provider: "keycloak", providerAccountId: tag }))?.id, owner);
  assert.equal(await adapter.getUserByAccount!({ provider: "keycloak", providerAccountId: "other" }), null);
  assert.equal(await adapter.getUserByEmail!(`${tag}-0@example.test`), null);
  await assert.rejects(() => Promise.resolve(adapter.linkAccount!({ userId: outsider, provider: "keycloak", providerAccountId: tag, type: "oidc" })));
  const token = randomUUID();
  await adapter.createSession!({ sessionToken: token, userId: owner, expires: new Date(Date.now() + 60000) });
  assert.equal((await resolveDatabaseSession(db, token))?.accountId, owner);
  assert.equal((await resolveDatabaseSession(db, token))?.mfaSatisfied, false);
  await db.account.update({ where: { id: owner }, data: { emailVerified: false } });
  assert.equal(await resolveDatabaseSession(db, token), null);
  await db.account.update({ where: { id: owner }, data: { emailVerified: true, status: "SUSPENDED" } });
  assert.equal(await resolveDatabaseSession(db, token), null);
  await db.account.update({ where: { id: owner }, data: { status: "ACTIVE", primaryEmail: `${tag}-changed@example.test` } });
  assert.equal((await adapter.getUserByAccount!({ provider: "keycloak", providerAccountId: tag }))?.id, owner);
  await adapter.deleteSession!(token);
  assert.equal(await resolveDatabaseSession(db, token), null);
  await adapter.createSession!({ sessionToken: token, userId: owner, expires: new Date(Date.now() - 1) });
  assert.equal(await resolveDatabaseSession(db, token), null);
  await revokeAccountSessions(db, owner, owner);
  assert.equal(await resolveDatabaseSession(db, token), null);
  await assert.rejects(() => Promise.resolve(adapter.createSession!({ sessionToken: token, userId: outsider, expires: new Date(Date.now() + 60000) })));
  // Relation deletion cascades the session; removing a provider link invalidates access.
  await adapter.createSession!({ sessionToken: token, userId: owner, expires: new Date(Date.now() + 60000) });
  await db.accountIdentity.delete({ where: { id: identity.id } });
  assert.equal(await resolveDatabaseSession(db, token), null);

  const company = await db.company.create({ data: { name: tag } }); companies.push(company.id);
  const secondCompany = await db.company.create({ data: { name: tag + "-other" } }); companies.push(secondCompany.id);
  const person = await db.person.findUniqueOrThrow({ where: { accountId: owner } });
  const relationship = await db.personCompanyRelationship.create({ data: { personId: person.id, companyId: company.id, relationshipType: "EMPLOYMENT", status: "ACTIVE" } });
  const definition = await db.recordDefinition.create({ data: { key: tag } }); definitions.push(definition.id);
  const version = await db.recordDefinitionVersion.create({ data: { recordDefinitionId: definition.id, version: 1, name: "Synthetic record", category: "TEST", context: "RELATIONSHIP", direction: "BIDIRECTIONAL", classification: "SENSITIVE", allowedCompanyRoles: [tag], personVisible: true } });
  const record = await db.record.create({ data: { definitionVersionId: version.id, context: "RELATIONSHIP", personId: person.id, companyId: company.id, relationshipId: relationship.id, title: tag, uploadedByAccountId: owner }, include: { definitionVersion: true } });
  assert.equal(await canReadStoredRecord(db, owner, record), true);
  assert.equal(await canReadStoredRecord(db, outsider, record), false);
  assert.equal(await canReadStoredRecord(db, lawyer, record), false);
  const role = await db.functionalRoleDefinition.create({ data: { code: tag, label: "Synthetic HR", capabilities: [] } });
  // Use an isolated code in a versioned definition; avoid altering global HR configuration.
  const current = await db.record.findUniqueOrThrow({ where: { id: record.id }, include: { definitionVersion: true } });
  const member = await db.companyMember.create({ data: { accountId: outsider, companyId: company.id, status: "ACTIVE" } });
  const roleGrant = await db.companyRoleGrant.create({ data: { companyMemberId: member.id, functionalRoleId: role.id } });
  assert.equal(await canReadStoredRecord(db, outsider, current), true);
  await db.companyRoleGrant.update({ where: { id: roleGrant.id }, data: { revokedAt: new Date() } });
  assert.equal(await canReadStoredRecord(db, outsider, current), false);
  await db.companyRoleGrant.update({ where: { id: roleGrant.id }, data: { revokedAt: null } });
  await db.companyMember.update({ where: { id: member.id }, data: { status: "REMOVED" } });
  assert.equal(await canReadStoredRecord(db, outsider, current), false);
  await db.companyMember.update({ where: { id: member.id }, data: { status: "ACTIVE", companyId: secondCompany.id } });
  assert.equal(await canReadStoredRecord(db, outsider, current), false);
  const legal = await db.legalAccessGrant.create({ data: { grantedToAccountId: lawyer, grantedByAccountId: owner, relationshipId: relationship.id, represents: "PERSON", allowedDefinitionIds: [definition.id], allowedCategories: ["TEST"], canView: true, startsAt: new Date(Date.now() - 1000), expiresAt: new Date(Date.now() + 60000), status: "ACTIVE" } });
  assert.equal(await canReadStoredRecord(db, lawyer, current), true);
  await db.legalAccessGrant.update({ where: { id: legal.id }, data: { allowedCategories: ["OTHER"] } });
  assert.equal(await canReadStoredRecord(db, lawyer, current), false);
  await db.legalAccessGrant.update({ where: { id: legal.id }, data: { allowedCategories: ["TEST"], expiresAt: new Date(Date.now() - 1) } });
  assert.equal(await canReadStoredRecord(db, lawyer, current), false);
  await db.legalAccessGrant.update({ where: { id: legal.id }, data: { expiresAt: new Date(Date.now() + 60000), revokedAt: new Date() } });
  assert.equal(await canReadStoredRecord(db, lawyer, current), false);
  const privateRecord = await db.record.create({ data: { definitionVersionId: version.id, context: "PERSON", personId: person.id, companyId: secondCompany.id, title: tag + " private", uploadedByAccountId: owner }, include: { definitionVersion: true } });
  assert.equal(await canReadStoredRecord(db, outsider, privateRecord), false);
  await db.governanceCapabilityGrant.create({ data: { accountId: outsider, capability: "platform.definitions.manage" } });
  assert.equal(await canReadStoredRecord(db, outsider, privateRecord), false);
  const nextVersion = await db.recordDefinitionVersion.create({ data: { recordDefinitionId: definition.id, version: 2, name: "Synthetic changed", category: "TEST", context: "RELATIONSHIP", direction: "BIDIRECTIONAL", classification: "SENSITIVE", allowedCompanyRoles: [], personVisible: false } });
  assert.notEqual(nextVersion.id, current.definitionVersionId);
  assert.equal(await canReadStoredRecord(db, owner, current), true);
  console.log("PASS: stable identity, no email linking, session expiration/revocation/unverified/suspended/unlinked rejection; person/tenant/role revocation, Legal Access scope/expiry/revocation, Governance not a record bypass, definition versions.");
} finally {
  await db.activityEvent.deleteMany({ where: { actorAccountId: { in: accounts } } });
  await db.record.deleteMany({ where: { uploadedByAccountId: { in: accounts } } });
  await db.legalAccessGrant.deleteMany({ where: { grantedByAccountId: { in: accounts } } });
  await db.personCompanyRelationship.deleteMany({ where: { companyId: { in: companies } } });
  await db.companyMember.deleteMany({ where: { accountId: { in: accounts } } });
  await db.company.deleteMany({ where: { id: { in: companies } } });
  await db.functionalRoleDefinition.deleteMany({ where: { code: tag } });
  await db.recordDefinitionVersion.deleteMany({ where: { recordDefinitionId: { in: definitions } } });
  await db.recordDefinition.deleteMany({ where: { id: { in: definitions } } });
  await db.person.deleteMany({ where: { accountId: { in: accounts } } });
  await db.account.deleteMany({ where: { id: { in: accounts } } });
  await db.$disconnect();
}
